sudo: required

services:
  - docker

before_install:
- docker info
- docker pull insighttoolkit/minimalpathextraction-test

script:
- mkdir ../itkSuperPixel-build
- docker run -v ./:/usr/src/itkSuperPixel -v ../itkSuperPixel-build:/usr/src/itkSuperPixel-build insighttoolkit/minimalpathextraction-test ./test/Docker/test.sh

